FROM ubuntu
RUN apt update && apt upgrade -y
RUN apt install python3 python3-pip cron -y
RUN mkdir /checker
COPY . /checker
WORKDIR /checker
RUN pip3 install -r req2.txt 
RUN echo "*/5 * * * * root cd /checker/ 2>&1 && /usr/bin/python3 /checker/main.py" >> /etc/crontab 
CMD cron && /bin/bash