FROM ubuntu
RUN apt update && apt upgrade -y
RUN apt install python3 cron -y
RUN mkdir /checker
RUN cp . /checker
WORKDIR /checker
RUN pip3 install -r req.txt
RUN echo "#testmessage q" >> /etc/crontab
RUN /etc/init.d/cron start
RUN echo "Always done, yep"
